# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b15fa4c8d1d577926f24010d0bb32cce46ed815913d4a9108a1f70c2325b4646c6f6de00fd0544a55e396831700ed476e6ae4692c603a46dd9c30f797a458c9

test:
  secret_key_base: edbbfc25cf78925383dd1d9cd9c5300e808fffe0d078e596add59543a36c0abae01b17808f938e1109e9dd3f7f79dbe6827ed5da990feae18c9d2595f7a0eacc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
